create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz not null default now()
);

insert into public.projects (name)
values ('General')
on conflict (name) do nothing;

alter table public.reports
  add column if not exists project_name text;

update public.reports
set project_name = 'General'
where project_name is null;

alter table public.reports
  alter column project_name set not null;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'reports_project_name_fkey'
  ) then
    alter table public.reports
      add constraint reports_project_name_fkey
      foreign key (project_name)
      references public.projects (name)
      on update cascade
      on delete restrict;
  end if;
end $$;

create index if not exists reports_project_name_idx
  on public.reports (project_name);
