create table if not exists public.reports (
  id bigint generated by default as identity primary key,
  report_user text not null,
  task_id text not null,
  task_name text not null,
  personal_description text not null,
  complexity text not null check (complexity in ('Low', 'Medium', 'High')),
  estimated_time numeric not null check (estimated_time >= 0),
  real_time numeric not null check (real_time >= 0),
  token_usage integer not null check (token_usage >= 0),
  models text[] not null check (cardinality(models) > 0),
  iterations integer not null check (iterations >= 0),
  code_quality integer not null check (code_quality between 0 and 5),
  code_quality_description text not null,
  created_at timestamptz not null default now()
);

create index if not exists reports_created_at_idx
  on public.reports (created_at desc);

insert into public.reports (
  report_user,
  task_id,
  task_name,
  personal_description,
  complexity,
  estimated_time,
  real_time,
  token_usage,
  models,
  iterations,
  code_quality,
  code_quality_description
)
select
  'Lucas Levandoski',
  '123123',
  'Data Processing',
  'This task involves processing large datasets to extract meaningful insights.',
  'High',
  5,
  2,
  15,
  array['GPT-4o', 'Claude 3.7 Sonnet'],
  3,
  5,
  'The code is well-structured, follows best practices, and is easy to maintain.'
where not exists (
  select 1
  from public.reports
);
